import Header from "../components/header";
import '../styles/global.css'
import '@fortawesome/fontawesome-svg-core/styles.css'
import Content from "../components/content";
import {ReactNode} from "react";
import Footer from "../components/footer";
import Providers from "../components/react_query_provider";

export const metadata = {
    title: 'Org manager',
    description: 'Generated by Next.js',
}

export default function RootLayout({children}: {
    children: ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <Header/>
        <Content>
            <Providers>
                {children}
            </Providers>
        </Content>
        <Footer/>
        </body>
        </html>
    )
}
