import Header from "../components/header";
import '../styles/global.css'
import Content from "../components/content";
import {ReactNode} from "react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <Content>
            {children}
        </Content>
      </body>
    </html>
  )
}
